### ISSUE TITLE
FIX: Wrong Spanish translations

### ISSUE THREAD

**Issue by anonymous1184** [ChaosMarc/PlugY#21]
The spanish translations seem to be mixed up with Italian.

https://github.com/ChaosMarc/PlugY/blob/29cbdbe02801a47054a31858ca79302af4fd364c/PlugYInstaller/PlugY/LocalizedStrings.ini#L29

Here's the file with the correct translations: [LocalizedStrings.txt](https://github.com/ChaosMarc/PlugY/files/4057110/LocalizedStrings.txt)

**Comment by ChaosMarc** [comment]
@anonymous1184 Thank you very much for pointing that out. I have fixed the translations by using your spanish translation for ESP and the current ESP translations as ITA.

I also created a POEditor project and linked it with this git repository so that future translations can be updated more easily: https://poeditor.com/projects/view?id=343405
